version: '3'
services:
    node:
        image: node:6.14.3-alpine
        ports:
            - 4200:4200
        networks: ['heroes']
        tty: true
        volumes:
            - ./project/www/${PROJNAME}:/wwwroot/ecommerce/base/production/current
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: root
volumes:
    esdata:
        driver: local

networks: {heroes: {}}
